package ink.codflow.sync.dao;

import ink.codflow.sync.entity.AccountDO;
import ink.codflow.sync.qo.AuthenticationQuery;

public interface AccountDOMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table account
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table account
     * @mbg.generated
     */
    int insert(AccountDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table account
     * @mbg.generated
     */
    int insertSelective(AccountDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table account
     * @mbg.generated
     */
    AccountDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table account
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AccountDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table account
     * @mbg.generated
     */
    int updateByPrimaryKey(AccountDO record);

    /**
     * @description: TODO
     * @param username void
     */
    AccountDO selectByName(String username);

    /**
     * @description: TODO
     * @param authenticationQuery
     * @return AccountDO
     */
    AccountDO getByAuth(AuthenticationQuery authenticationQuery);
}