package ink.codflow.sync.dao;

import ink.codflow.sync.entity.AccountDO;
import ink.codflow.sync.qo.AuthenticationQuery;

public interface AccountDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int insert(AccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int insertSelective(AccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    AccountDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int updateByPrimaryKeySelective(AccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int updateByPrimaryKey(AccountDO record);

    
    /**
     * @description: TODO
     * @param username void
     */
    AccountDO selectByName(String username);

    /**
     * @description: TODO
     * @param authenticationQuery
     * @return AccountDO
     */
    AccountDO getByAuth(AuthenticationQuery authenticationQuery);
}