package ink.codflow.sync.dao;

import java.util.List;

import ink.codflow.sync.entity.ClientAccessDataDO;

public interface ClientAccessDataDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access_data
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access_data
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int insert(ClientAccessDataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access_data
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int insertSelective(ClientAccessDataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access_data
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    ClientAccessDataDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access_data
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int updateByPrimaryKeySelective(ClientAccessDataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access_data
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int updateByPrimaryKey(ClientAccessDataDO record);


    /**
     * @description: TODO
     * @param clientAccessId
     * @return List<ClientAccessDataDO>
     */
    List<ClientAccessDataDO> selectByClientAccessId(Integer clientAccessId);
}