package ink.codflow.sync.dao;

import org.apache.ibatis.annotations.Param;

import ink.codflow.sync.entity.ClientAccountDO;

public interface ClientAccountDOMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fk_client_account
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fk_client_account
     * @mbg.generated
     */
    int insert(ClientAccountDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fk_client_account
     * @mbg.generated
     */
    int insertSelective(ClientAccountDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fk_client_account
     * @mbg.generated
     */
    ClientAccountDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fk_client_account
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ClientAccountDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table fk_client_account
     * @mbg.generated
     */
    int updateByPrimaryKey(ClientAccountDO record);

    /**
     * @description: TODO
     * @param accountId
     * @param clientId
     * @return int
     */
    int deleteByAccountIdAndClientId(@Param("accountId")String accountId, @Param("clientId")Integer clientId);
}