package ink.codflow.sync.dao;

import ink.codflow.sync.entity.ClientAccessDO;

public interface ClientAccessDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int insert(ClientAccessDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int insertSelective(ClientAccessDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    ClientAccessDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int updateByPrimaryKeySelective(ClientAccessDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int updateByPrimaryKey(ClientAccessDO record);
}