package ink.codflow.sync.dao;

import java.util.List;

import ink.codflow.sync.entity.ClientAccessDataDO;

public interface ClientAccessDataDOMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table client_access_data
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table client_access_data
     * @mbg.generated
     */
    int insert(ClientAccessDataDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table client_access_data
     * @mbg.generated
     */
    int insertSelective(ClientAccessDataDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table client_access_data
     * @mbg.generated
     */
    ClientAccessDataDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table client_access_data
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ClientAccessDataDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table client_access_data
     * @mbg.generated
     */
    int updateByPrimaryKey(ClientAccessDataDO record);

    /**
     * @description: TODO
     * @param clientAccessId
     * @return List<ClientAccessDataDO>
     */
    List<ClientAccessDataDO> selectByClientAccessId(Integer clientAccessId);
}