package ink.codflow.sync.dao;

import ink.codflow.sync.entity.ClientAccessDO;

public interface ClientAccessDOMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table client_access
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table client_access
     * @mbg.generated
     */
    int insert(ClientAccessDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table client_access
     * @mbg.generated
     */
    int insertSelective(ClientAccessDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table client_access
     * @mbg.generated
     */
    ClientAccessDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table client_access
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ClientAccessDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table client_access
     * @mbg.generated
     */
    int updateByPrimaryKey(ClientAccessDO record);
}