package ink.codflow.sync.dao;

import ink.codflow.sync.entity.ClientAccountDO;

public interface ClientAccountDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_client_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_client_account
     *
     * @mbg.generated
     */
    int insert(ClientAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_client_account
     *
     * @mbg.generated
     */
    int insertSelective(ClientAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_client_account
     *
     * @mbg.generated
     */
    ClientAccountDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_client_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ClientAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fk_client_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ClientAccountDO record);
}