package ink.codflow.sync.dao;

import ink.codflow.sync.entity.EndpointDO;

public interface EndpointDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endpoint
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endpoint
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int insert(EndpointDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endpoint
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int insertSelective(EndpointDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endpoint
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    EndpointDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endpoint
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int updateByPrimaryKeySelective(EndpointDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endpoint
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int updateByPrimaryKey(EndpointDO record);
}