package ink.codflow.sync.dao;

import ink.codflow.sync.entity.EndpointDetailDO;

public interface EndpointDetailDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endpoint_detail
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endpoint_detail
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int insert(EndpointDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endpoint_detail
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int insertSelective(EndpointDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endpoint_detail
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    EndpointDetailDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endpoint_detail
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int updateByPrimaryKeySelective(EndpointDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endpoint_detail
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int updateByPrimaryKey(EndpointDetailDO record);
}