package ink.codflow.sync.dao;

import ink.codflow.sync.entity.EndpointDO;

public interface EndpointDOMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table endpoint
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table endpoint
     * @mbg.generated
     */
    int insert(EndpointDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table endpoint
     * @mbg.generated
     */
    int insertSelective(EndpointDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table endpoint
     * @mbg.generated
     */
    EndpointDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table endpoint
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EndpointDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table endpoint
     * @mbg.generated
     */
    int updateByPrimaryKey(EndpointDO record);
}