package ink.codflow.sync.dao;

import ink.codflow.sync.entity.EndpointDetailDO;

public interface EndpointDetailDOMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table endpoint_detail
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table endpoint_detail
     * @mbg.generated
     */
    int insert(EndpointDetailDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table endpoint_detail
     * @mbg.generated
     */
    int insertSelective(EndpointDetailDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table endpoint_detail
     * @mbg.generated
     */
    EndpointDetailDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table endpoint_detail
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EndpointDetailDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table endpoint_detail
     * @mbg.generated
     */
    int updateByPrimaryKey(EndpointDetailDO record);
}