package ink.codflow.sync.dao;

import ink.codflow.sync.entity.LinkDO;

public interface LinkDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int insert(LinkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Sun Oct 04 17:31:24 CST 2020
     */
    int insertSelective(LinkDO record);
}