package ink.codflow.sync.entity;

import java.io.Serializable;
import java.util.Date;

public class AccountDO implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.id
     * @mbg.generated
     */
    private String id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.username
     * @mbg.generated
     */
    private String username;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.password
     * @mbg.generated
     */
    private String password;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.type
     * @mbg.generated
     */
    private String type;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.create_time
     * @mbg.generated
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.update_time
     * @mbg.generated
     */
    private Date updateTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table account
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.id
     * @return  the value of account.id
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.id
     * @param id  the value for account.id
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.username
     * @return  the value of account.username
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.username
     * @param username  the value for account.username
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.password
     * @return  the value of account.password
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.password
     * @param password  the value for account.password
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.type
     * @return  the value of account.type
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.type
     * @param type  the value for account.type
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.create_time
     * @return  the value of account.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.create_time
     * @param createTime  the value for account.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.update_time
     * @return  the value of account.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.update_time
     * @param updateTime  the value for account.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}