package ink.codflow.sync.entity;

import java.io.Serializable;

public class ClientAccessDataDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_access_data.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_access_data.client_access_id
     *
     * @mbg.generated
     */
    private Integer clientAccessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_access_data.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_access_data.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table client_access_data
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_access_data.id
     *
     * @return the value of client_access_data.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_access_data.id
     *
     * @param id the value for client_access_data.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_access_data.client_access_id
     *
     * @return the value of client_access_data.client_access_id
     *
     * @mbg.generated
     */
    public Integer getClientAccessId() {
        return clientAccessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_access_data.client_access_id
     *
     * @param clientAccessId the value for client_access_data.client_access_id
     *
     * @mbg.generated
     */
    public void setClientAccessId(Integer clientAccessId) {
        this.clientAccessId = clientAccessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_access_data.type
     *
     * @return the value of client_access_data.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_access_data.type
     *
     * @param type the value for client_access_data.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_access_data.value
     *
     * @return the value of client_access_data.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_access_data.value
     *
     * @param value the value for client_access_data.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}