package ink.codflow.sync.entity;

import java.io.Serializable;

public class EndpointDO implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column endpoint.id
     * @mbg.generated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column endpoint.client_id
     * @mbg.generated
     */
    private Integer clientId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column endpoint.client_access_id
     * @mbg.generated
     */
    private Integer clientAccessId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column endpoint.name
     * @mbg.generated
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column endpoint.root
     * @mbg.generated
     */
    private String root;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column endpoint.create_time
     * @mbg.generated
     */
    private String createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column endpoint.update_time
     * @mbg.generated
     */
    private String updateTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column endpoint.state
     * @mbg.generated
     */
    private String state;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table endpoint
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column endpoint.id
     * @return  the value of endpoint.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column endpoint.id
     * @param id  the value for endpoint.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column endpoint.client_id
     * @return  the value of endpoint.client_id
     * @mbg.generated
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column endpoint.client_id
     * @param clientId  the value for endpoint.client_id
     * @mbg.generated
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column endpoint.client_access_id
     * @return  the value of endpoint.client_access_id
     * @mbg.generated
     */
    public Integer getClientAccessId() {
        return clientAccessId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column endpoint.client_access_id
     * @param clientAccessId  the value for endpoint.client_access_id
     * @mbg.generated
     */
    public void setClientAccessId(Integer clientAccessId) {
        this.clientAccessId = clientAccessId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column endpoint.name
     * @return  the value of endpoint.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column endpoint.name
     * @param name  the value for endpoint.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column endpoint.root
     * @return  the value of endpoint.root
     * @mbg.generated
     */
    public String getRoot() {
        return root;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column endpoint.root
     * @param root  the value for endpoint.root
     * @mbg.generated
     */
    public void setRoot(String root) {
        this.root = root == null ? null : root.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column endpoint.create_time
     * @return  the value of endpoint.create_time
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column endpoint.create_time
     * @param createTime  the value for endpoint.create_time
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column endpoint.update_time
     * @return  the value of endpoint.update_time
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column endpoint.update_time
     * @param updateTime  the value for endpoint.update_time
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column endpoint.state
     * @return  the value of endpoint.state
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column endpoint.state
     * @param state  the value for endpoint.state
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}