package ink.codflow.sync.entity;

import java.io.Serializable;

public class EndpointDetailDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endpoint_detail.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endpoint_detail.endpoint_id
     *
     * @mbg.generated
     */
    private String endpointId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endpoint_detail.usage
     *
     * @mbg.generated
     */
    private Long usage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endpoint_detail.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table endpoint_detail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endpoint_detail.id
     *
     * @return the value of endpoint_detail.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endpoint_detail.id
     *
     * @param id the value for endpoint_detail.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endpoint_detail.endpoint_id
     *
     * @return the value of endpoint_detail.endpoint_id
     *
     * @mbg.generated
     */
    public String getEndpointId() {
        return endpointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endpoint_detail.endpoint_id
     *
     * @param endpointId the value for endpoint_detail.endpoint_id
     *
     * @mbg.generated
     */
    public void setEndpointId(String endpointId) {
        this.endpointId = endpointId == null ? null : endpointId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endpoint_detail.usage
     *
     * @return the value of endpoint_detail.usage
     *
     * @mbg.generated
     */
    public Long getUsage() {
        return usage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endpoint_detail.usage
     *
     * @param usage the value for endpoint_detail.usage
     *
     * @mbg.generated
     */
    public void setUsage(Long usage) {
        this.usage = usage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endpoint_detail.status
     *
     * @return the value of endpoint_detail.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endpoint_detail.status
     *
     * @param status the value for endpoint_detail.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}