package ink.codflow.sync.entity;

import java.io.Serializable;
import java.util.Date;

public class LinkDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.source_endpoint_id
     *
     * @mbg.generated
     */
    private Integer sourceEndpointId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.target_endpoint_id
     *
     * @mbg.generated
     */
    private Integer targetEndpointId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.udpate_time
     *
     * @mbg.generated
     */
    private Date udpateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table link
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.id
     *
     * @return the value of link.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.id
     *
     * @param id the value for link.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.source_endpoint_id
     *
     * @return the value of link.source_endpoint_id
     *
     * @mbg.generated
     */
    public Integer getSourceEndpointId() {
        return sourceEndpointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.source_endpoint_id
     *
     * @param sourceEndpointId the value for link.source_endpoint_id
     *
     * @mbg.generated
     */
    public void setSourceEndpointId(Integer sourceEndpointId) {
        this.sourceEndpointId = sourceEndpointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.target_endpoint_id
     *
     * @return the value of link.target_endpoint_id
     *
     * @mbg.generated
     */
    public Integer getTargetEndpointId() {
        return targetEndpointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.target_endpoint_id
     *
     * @param targetEndpointId the value for link.target_endpoint_id
     *
     * @mbg.generated
     */
    public void setTargetEndpointId(Integer targetEndpointId) {
        this.targetEndpointId = targetEndpointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.create_time
     *
     * @return the value of link.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.create_time
     *
     * @param createTime the value for link.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.udpate_time
     *
     * @return the value of link.udpate_time
     *
     * @mbg.generated
     */
    public Date getUdpateTime() {
        return udpateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.udpate_time
     *
     * @param udpateTime the value for link.udpate_time
     *
     * @mbg.generated
     */
    public void setUdpateTime(Date udpateTime) {
        this.udpateTime = udpateTime;
    }
}